# Generated by Django 3.1.7 on 2021-04-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='api.post'),
        ),
    ]
