# Generated by Django 3.1.7 on 2021-04-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='post',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
            preserve_default=False,
        ),
    ]
