# Generated by Django 3.1.7 on 2021-04-04 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_upvotepost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='api.post'),
        ),
    ]
